name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表格林乔治时间，加上8之后就是北京时间：1点-->9点
    # 格式为： minute(0-59) hour(0-23) day(1-31) month(1-12) week(0-6)
    - cron: '0 1 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: weixin
        run: |
          python3 main.py
